AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  one-nz-poc
  SAM template for TestOrchestratorLambda

Parameters:
  ClaudeModelIdParameter:
    Type: String
    Default: anthropic.claude-3-5-sonnet-20241022-v2:0
    Description: The Bedrock Model ID for Claude.

Globals:
  Function:
    Timeout: 30
    MemorySize: 256 # Adjusted memory
    Runtime: nodejs18.x # Updated runtime
    Environment:
      Variables:
        CLAUDE_MODEL_ID: !Ref ClaudeModelIdParameter
        # Add other necessary environment variables here

Resources:
  TestOrchestratorLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Zip
      CodeUri: ./ # Assumes build output (dist/) is at the root for SAM
      Handler: dist/index.handler # Points to the compiled JS file
      Architectures:
        - x86_64
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: !Sub 'arn:aws:bedrock:${AWS::Region}:${AWS::AccountId}:model/${ClaudeModelIdParameter}'
        # IAM policy for CloudWatch Logs will be automatically created by SAM based on the function name
      Events:
        TestInvoke: # Optional: Defines an API Gateway trigger if needed later
          Type: Api
          Properties:
            Path: /orchestrate
            Method: post

Outputs:
  TestOrchestratorLambdaArn:
    Description: 'ARN of the TestOrchestratorLambda function'
    Value: !GetAtt TestOrchestratorLambdaFunction.Arn
  TestOrchestratorLambdaIamRoleArn:
    Description: 'IAM Role ARN for the TestOrchestratorLambda function'
    Value: !GetAtt TestOrchestratorLambdaFunctionRole.Arn # Note: SAM auto-creates the role
